### ISSUE TITLE
Configure esmini via environment variables and default directory paths

### ISSUE THREAD

**Issue by doganulus** [esmini/esmini#645]
We are interested in cloud-native simulation and testing for automated driving applications. We did an experiment with containerized `esmini` using `podman`. For example, a recent version of `podman` allows the following pod description ([source](https://github.com/bounverif/esmini/blob/main/kubes/example-alks.yml)). 

In the pod description, the `ghcr.io/bounverif/esmini` container uses a custom shell script to run the `esmini` executable over all scenarios copied on a standard location (`/var/esmini/scenarios`) and output simulation artifacts to a standard location (`/var/esmini/data`). Pod descriptions allow binding these locations mounted locally or as container volumes. 

Overall I am happy with my experience but still see some room for `esmini` for containerized applications:

1. Enable configuring `esmini` using environment variables (e.g. `ESMINI_FIXED_TIMESTEP`). Environment variables can be overridden by command line options as a usual practice.
2. Determine default paths for the scenario, catalog, result, and config directories for `esmini` on Linux. Default paths should be configurable via environment variables.

```yaml
# https://github.com/bounverif/esmini/blob/main/kubes/example-alks.yml

apiVersion: v1
kind: Pod
metadata:
  name: esmini-cloud-native
  labels:
    app: esmini
spec:
  restartPolicy: Never
  initContainers:
    - name: xosc-scenarios
      image: ghcr.io/bounverif/xosc-scenarios-alks:latest
      imagePullPolicy: Always
      command: ['sh', '-c', 'cp -r /opt/xosc/scenarios/ /var/esmini/']
      volumeMounts:
        - name: xosc-scenarios
          mountPath: /var/esmini/scenarios
  containers:
    - name: esmini
      image: ghcr.io/bounverif/esmini:latest
      imagePullPolicy: Always
      env:
        - name: ESMINI_FIXED_TIMESTEP
          value: 0.01
      volumeMounts:
        - name: xosc-scenarios
          mountPath: /var/esmini/scenarios
        - name: results
          mountPath: /var/esmini/data
  volumes:
    - name: xosc-scenarios
      emptyDir: {}
    - name: results
      hostPath: 
        path: ./results
        type: DirectoryOrCreate
```

You can also run this pod using the command:

```sh
podman kube play --replace https://raw.githubusercontent.com/bounverif/esmini/refs/heads/main/kubes/example-alks.yml
```
This will create a `results` directory on your filesystem with ALKS simulation data. 

Finally, the following command will delete the pod from your system. Local directories would remain.

```sh
podman kube play --down https://raw.githubusercontent.com/bounverif/esmini/refs/heads/main/kubes/example-alks.yml
```

**Comment by eknabevcc** [comment]
Thanks for sharing. This is interesting ideas. 

We're currently looking into at least offering a config file where default option values can be specified, e.g. window, logfile path etc.

Also, we're considering environment variables. But according to current thinking we'd prefer finding out location of the esmini app (quite easy) or the shared library (when esmini is linked as lib), which is a bit tricky to my understanding. If solved and given that the config file is stored at a specific location relative the esmini app and lib, the config would easily be located and user settings can be retrieved from it.

**Comment by doganulus** [comment]
One of our goals is to use `esmini` in headless mode inside containers, so we are very much interested in cloud-native configuration styles. [Environment variables](https://12factor.net/config), [configuration dropins/overrides](https://uapi-group.org/specifications/specs/configuration_files_specification/), and default file locations (`/etc`, `/run`, `/usr`) are mechanisms mainly used for this purpose. 

Relative locations make this use case harder, and we could need to write fragile wrapper/glue code to use `esmini` as above. If we could find a seamless solution between the two use cases, that would be ideal. 

Do you already have a draft/PR for config files?

**Comment by eknabevcc** [comment]
Unfortunately I'm not familiar with the configuration dropins/overrides concept. 

Our idea is simple (at least at drawingboard): Just add a single config file in yaml format. This file can include a list of specified option value pairs, mirroring the [launch options](https://esmini.github.io/#_esmini). 

Example:

```
esmini options:
    window: 60 60 800 400
    camera_mode: flex-orbit
```

The challenge we're investigating is whether we need to rely on an environment variable to find this config file, or if we can conclude (relative) location from the location of the esmini application or shared library (trickier).

Would that address your need, or something would be missing?

**Comment by doganulus** [comment]
I think an environment variable called `ESMINI_CONFIG_PATH` would be very useful. Still, it can be set to a relative path as the default for the application. The shared library case may prefer an absolute path, though (easier in Linux, don't know Windows). But let it to the library user.

For a potential design, let's assume we have the configuration file is called `esmini.yml`, and add an environment variable called `ESMINI_CONFIG_PATH` to configure its location. You may set a default value if this variable is unset or empty, for example, `../config`. When `esmini` runs, the application loads the config file first and parses command line options to override these defaults. 

For container use cases, I would love this design to be extended to support multiple configuration file locations, as we do not usually alter files inside the container. For such uses, we must be able to define `ESMINI_CONFIG_PATH=/usr/lib/esmini/config:/etc/esmini` to search for multiple `esmini.yml` and load them in the given order if they exist. Therefore, Esmini options set in `/etc/esmini/esmini.yml` would override values set in `/usr/lib/esmini/config/esmini.yml`. I think this wouldn't bring a big additional implementation effort.

Finally, the ability to override every Esmini option via `ESMINI_XXX` environment variables would be another great feature on top of this design.

The proposed hierarchy to configure Esmini:
1. Config file(s)
2. Environment variables
3. Command line options

P.S. This is already a good base for the discussion. So I didn't include drop-ins to complicate it further. May not be needed for the Esmini application.

**Comment by eknabevcc** [comment]
Thanks for good input. After some internal discussions current idea:
- support multiple config files
- for single value options: Last entry wins
- for options supporting multiple values: Add all values in reverse order of appearance
  - example: `--path` which will make esmini look for assets in specified folder(s), starting from last entry, stop on found
- initially support only one environment variable: `ESMINI_CONFIG_PATH`
  - the variable can, as proposed, include multiple references to config files
  - that way all desired options can be controlled from a user config file
- command line overriding any config file option

@rizsaq: something wrong or missing?

**Comment by doganulus** [comment]
Sounds good. It is easy to add environment variables later if desired.

It is possible in YAML to group `esmini` options hierarchically. Do you think this is a good idea?

I am not familiar with all options, but for example:

```yaml
# esmini.yml

window:
  size: 60 60 1600 900
  borderless: false
  fullscreen: false
  bounding_boxes: true
  headless: false

graphics:
  aa_mode: 3
  enforce_generate_model: false

simulation:
  scenario: scenario.xosc
  fixed_timestep: 0.1
  collision: true # enable collision check
  disable_controllers
  record:
    filename:

logging:
  filename: 
  
```

**Comment by eknabevcc** [comment]
We thought similar. One common config file. 1-1 mapping of available options. Trying to harmonize parsing and applying the options. Potentially and optionally the options can be structured lightweight way by comments, maybe good enough.

```yaml
# config.yml
esmini:
  # visuals
  window: 60 60 1600 900
  camera_mode: flex-orbit
  # logging
  logfile_path: /tmp/my_log.txt
  
replayer:
  window: 60 60 800 400

odrviewer:
  window: 60 60 800 400
  density: 3
```
